[2025-04-12T02:06:17.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-12T02:06:17.709+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-12T02:06:17.709+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-12T02:06:17.722+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-11 00:00:00+00:00
[2025-04-12T02:06:17.724+0000] {standard_task_runner.py:60} INFO - Started process 263 to run task
[2025-04-12T02:06:17.726+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-11T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmpc11p2to6']
[2025-04-12T02:06:17.727+0000] {standard_task_runner.py:88} INFO - Job 191: Subtask load_to_postgres
[2025-04-12T02:06:17.754+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [running]> on host 6ca683c63410
[2025-04-12T02:06:17.826+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T00:00:00+00:00'
[2025-04-12T02:06:17.857+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-12T02:07:36.871+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/youtube_comment_pipeline.py", line 137, in bulk_insert_comments
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-12T02:07:36.903+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250411T000000, start_date=20250412T020617, end_date=20250412T020736
[2025-04-12T02:07:36.916+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 191 for task load_to_postgres (connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 263)
[2025-04-12T02:07:36.946+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T02:07:36.961+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T02:25:20.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-20T02:25:20.961+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [queued]>
[2025-04-20T02:25:20.961+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-20T02:25:20.969+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-11 00:00:00+00:00
[2025-04-20T02:25:20.972+0000] {standard_task_runner.py:60} INFO - Started process 2298 to run task
[2025-04-20T02:25:20.974+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-11T00:00:00+00:00', '--job-id', '583', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmp3220xqs3']
[2025-04-20T02:25:20.976+0000] {standard_task_runner.py:88} INFO - Job 583: Subtask load_to_postgres
[2025-04-20T02:25:21.010+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-11T00:00:00+00:00 [running]> on host 7e480c288e12
[2025-04-20T02:25:21.066+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T00:00:00+00:00'
[2025-04-20T02:25:21.080+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-20T02:25:23.833+0000] {logging_mixin.py:188} INFO - Successfully batch-inserted 112 comments.
[2025-04-20T02:25:23.834+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-20T02:25:23.839+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250411T000000, start_date=20250420T022520, end_date=20250420T022523
[2025-04-20T02:25:23.882+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-20T02:25:23.892+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
