[2025-04-12T04:08:31.205+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-12T04:08:31.208+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-12T04:08:31.208+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-12T04:08:31.213+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-10 00:00:00+00:00
[2025-04-12T04:08:31.215+0000] {standard_task_runner.py:60} INFO - Started process 2425 to run task
[2025-04-12T04:08:31.217+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmpbs30xt5x']
[2025-04-12T04:08:31.218+0000] {standard_task_runner.py:88} INFO - Job 200: Subtask load_to_postgres
[2025-04-12T04:08:31.281+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [running]> on host 4f2803ee1ba2
[2025-04-12T04:08:31.335+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-12T04:08:31.360+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-12T04:09:46.371+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/youtube_comment_pipeline.py", line 137, in bulk_insert_comments
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-12T04:09:46.404+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250410T000000, start_date=20250412T040831, end_date=20250412T040946
[2025-04-12T04:09:46.418+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 200 for task load_to_postgres (connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 2425)
[2025-04-12T04:09:46.466+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T04:09:46.484+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T02:46:44.827+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-20T02:46:44.830+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-20T02:46:44.830+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-20T02:46:44.835+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-10 00:00:00+00:00
[2025-04-20T02:46:44.837+0000] {standard_task_runner.py:60} INFO - Started process 3401 to run task
[2025-04-20T02:46:44.839+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '675', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmpbd21n0jw']
[2025-04-20T02:46:44.840+0000] {standard_task_runner.py:88} INFO - Job 675: Subtask load_to_postgres
[2025-04-20T02:46:44.864+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-10T00:00:00+00:00 [running]> on host 7e480c288e12
[2025-04-20T02:46:44.903+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-20T02:46:44.922+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-20T02:46:51.350+0000] {logging_mixin.py:188} INFO - Successfully batch-inserted 1345 comments.
[2025-04-20T02:46:51.354+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-20T02:46:51.371+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250410T000000, start_date=20250420T024644, end_date=20250420T024651
[2025-04-20T02:46:51.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-20T02:46:51.422+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
