[2025-04-12T04:08:23.386+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-12T04:08:23.389+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-12T04:08:23.389+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-12T04:08:23.393+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-08 00:00:00+00:00
[2025-04-12T04:08:23.396+0000] {standard_task_runner.py:60} INFO - Started process 2421 to run task
[2025-04-12T04:08:23.397+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmpbr2fh8np']
[2025-04-12T04:08:23.398+0000] {standard_task_runner.py:88} INFO - Job 198: Subtask load_to_postgres
[2025-04-12T04:08:23.418+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [running]> on host 4f2803ee1ba2
[2025-04-12T04:08:23.447+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-12T04:08:23.460+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-12T04:09:39.176+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/youtube_comment_pipeline.py", line 137, in bulk_insert_comments
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2025-04-12T04:09:39.193+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250408T000000, start_date=20250412T040823, end_date=20250412T040939
[2025-04-12T04:09:39.203+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 198 for task load_to_postgres (connection to server at "database-1.cb0kcw8qg146.us-east-1.rds.amazonaws.com" (3.213.99.62), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 2421)
[2025-04-12T04:09:39.213+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T04:09:39.224+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T02:39:48.659+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-20T02:39:48.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-20T02:39:48.662+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-20T02:39:48.666+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-08 00:00:00+00:00
[2025-04-20T02:39:48.668+0000] {standard_task_runner.py:60} INFO - Started process 3048 to run task
[2025-04-20T02:39:48.670+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '652', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmp7ub4z4qo']
[2025-04-20T02:39:48.671+0000] {standard_task_runner.py:88} INFO - Job 652: Subtask load_to_postgres
[2025-04-20T02:39:48.690+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres scheduled__2025-04-08T00:00:00+00:00 [running]> on host 7e480c288e12
[2025-04-20T02:39:48.719+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-20T02:39:48.729+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-20T02:39:52.402+0000] {logging_mixin.py:188} INFO - Successfully batch-inserted 149 comments.
[2025-04-20T02:39:52.404+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-20T02:39:52.420+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=youtube_comment_pipeline_us_stocks_daily, task_id=load_to_postgres, execution_date=20250408T000000, start_date=20250420T023948, end_date=20250420T023952
[2025-04-20T02:39:52.463+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-20T02:39:52.477+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
