[2025-04-12T13:59:50.921+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-12T13:58:51.042234+00:00 [queued]>
[2025-04-12T13:59:50.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-12T13:58:51.042234+00:00 [queued]>
[2025-04-12T13:59:50.931+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-12T13:59:50.945+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bertopic> on 2025-04-12 13:58:51.042234+00:00
[2025-04-12T13:59:50.960+0000] {standard_task_runner.py:60} INFO - Started process 83338 to run task
[2025-04-12T13:59:50.968+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'run_bertopic', 'manual__2025-04-12T13:58:51.042234+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpvcbc61a7']
[2025-04-12T13:59:50.972+0000] {standard_task_runner.py:88} INFO - Job 245: Subtask run_bertopic
[2025-04-12T13:59:51.020+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-12T13:58:51.042234+00:00 [running]> on host 09c1abf4dbfb
[2025-04-12T13:59:51.101+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='run_bertopic' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T13:58:51.042234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T13:58:51.042234+00:00'
[2025-04-12T13:59:51.166+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-04-12T13:59:51.167+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
[2025-04-12T14:20:57.557+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-12T14:20:57.568+0000] {process_utils.py:131} INFO - Sending 15 to group 83338. PIDs of all processes in the group: [83338]
[2025-04-12T14:20:57.569+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 83338
[2025-04-12T14:20:57.571+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-12T14:20:57.710+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=83338, status='terminated', exitcode=0, started='13:59:50') (83338) terminated with exit code 0
